app = "football-stock-exchange"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3070
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

[env]
  PORT = "3070"
  TXLINE_MOCK = "true"
  SOLANA_NETWORK = "devnet"
